"""Writes VIDEO_SCRIPT.md from the pipeline outputs. Every spoken number cites the file it came from.

Physics lines come only from `runway.physics_lines` (Wear). Run by the demo after the
artifacts exist, so the script never drifts from the files it cites.
"""
from __future__ import annotations

import csv
from collections import Counter

from runway import physics_lines
from runway.paths import OUTPUTS, ROOT, read_json


def _read(rel):
    p = OUTPUTS / rel
    return read_json(p) if p.exists() else None


def _physics(needle: str) -> str:
    for text, src in physics_lines.lines():
        if needle in text:
            return f"{text} [`{src}`]"
    return "**Missing from PHYSICS_LINES.md; not spoken.**"


def rows() -> list[tuple[str, str, str, str]]:
    m = _read("track2/metrics.json") or {}
    ladder = _read("track2/ladder.json") or {}
    bench = _read("bench/allocate.json") or {}
    summ = _read("replay/summary.json") or {}
    flags = read_json(ROOT / "handoff" / "hit_flags.json") if (ROOT / "handoff" / "hit_flags.json").exists() else {}
    blast = _read("physics/blast_overlay.json") or {}
    dt = OUTPUTS / "demo" / "decision_table.csv"
    moves = Counter(r["assignment"] for r in csv.DictReader(dt.open())) if dt.exists() else Counter()
    caught = [f["interval_end_local"].split()[0] for f in flags.get("published_4cp", []) if f["hit"]]
    sizes = bench.get("sizes", {})
    bench_line = ", ".join(f"{v['p50_ms']:.0f} ms at {int(k):,} units" for k, v in sizes.items())
    chosen = ladder.get("chosen_n")
    rung = ladder.get("rungs", {}).get(str(chosen), {})
    return [
        ("0:00–0:30", "Wear", "Two units: same kWh, different enclosure °C, different capacity loss. Reserve untouched.",
         _physics("Two synthetic units")),
        ("0:30–1:40", "Wear", "2025 candidate days vs published 4CP; labeled \"system-load proxy, score not probability\"",
         f"{flags.get('n_calls', '—')} candidate days; {len(caught)} of {len(flags.get('published_4cp', []))} published 4CP "
         f"intervals caught ({', '.join(caught)}) [`handoff/hit_flags.json`]. " + _physics("a kWh on a missed call") + " "
         + _physics("of summer call wear lands on calls that missed") + " " + _physics("small-cell LFP data")),
        ("1:40–2:20", "Machine", "`decision_table.csv`, the 2,000-unit saturation row, benchmark, BLAST overlay",
         f"\"{sum(moves.values())} units changed setpoint on the re-solve: {moves.get('offline', 0)} went offline, "
         f"the rest took up their power\" [`outputs/demo/decision_table.csv`]. \"allocate() p50: {bench_line} on {bench.get('cpu', '—')}\" "
         f"[`outputs/bench/allocate.json`]. " + _physics("At 2,000 units asked for 40 MW") + " "
         + (_physics("matches BLAST-Lite") if blast.get("status") == "ok" else "BLAST overlay failed; not shown.")),
        ("2:20–3:40", "Machine", "Live `python -m runway.demo --seed 7 --fault offline_wave`, then 10 s of the restart log",
         f"\"{m.get('n_units', '—'):,} synthetic units, {m.get('mw_requested', 0):.0f} MW requested\" [`outputs/track2/metrics.json`]. "
         f"\"The {100 * m.get('fraction_offline', 0):.0f}% of units holding the largest setpoints go offline.\" "
         f"\"Shortfall {m.get('shortfall_kw', 0) / 1000:.1f} MW, reserve violations {m.get('reserve_violations', '—')}, "
         f"re-solved in {m.get('resole_latency_ms', 0):.0f} ms of wall clock\" [`metrics.json`]. "
         f"\"{chosen:,} is the largest rung under one second: p50 {rung.get('p50_ms', 0):.0f} ms\" [`outputs/track2/ladder.json`]. "
         "\"Workers are async actors in one process.\" Restart: \"the dispatcher was SIGKILLed between the journal write and the "
         "commit of seq 3; on restart it re-sent seq 3 once, and each seq committed exactly once\" [`outputs/track2/restart.log`]." if chosen else "Ladder missing."),
        ("3:40–4:30", "Wear", "Replay at the feasible MW, the over-call fixture, the flip flag",
         _physics("Summer replay at") + " " + _physics("On the hero calls, Runway uses") + " " + _physics("Over-call fixture") + " "
         + _physics("ranking_flipped_across_assumption_sets")),
        ("4:30–5:00", "Machine", "README command from a clean venv with the network off",
         "\"One command. Reserve fraction 0.30, replacement at 0.70, and a 4,000-unit fleet are our assumptions\" "
         "[`README.md`, `runway/contracts.py`]. Fallback recording [`outputs/demo/fallback_recording.txt`]."),
    ]


def write() -> None:
    lines = [
        "# Video script (five minutes, seed 7, one recording)",
        "",
        "Generated by `runway/video_script.py` from the pipeline outputs. **Synthetic fleet** is on screen the whole time. "
        "ERCOT 2025 dates, load, forecasts, and 4CP intervals are real public data; there is no Base telemetry. Every spoken "
        "number cites a file. Physics lines come only from `PHYSICS_LINES.md`. Simulated call time and wall-clock latency are "
        "labeled as separate clocks.",
        "",
        "| Time | Owner | On screen | Spoken (citation) |",
        "| --- | --- | --- | --- |",
    ]
    lines += [f"| {t} | {o} | {s} | {w} |" for t, o, s, w in rows()]
    (ROOT / "VIDEO_SCRIPT.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    write()
